/**
 * Ruta bajo `public/bible/` para cada libro en JSON Huichol (formato *_capitulos_versiculos).
 * Los nombres coinciden con `bookOrder` / UI en español.
 */
export const HUICHOL_SPANISH_BOOK_TO_JSON: Readonly<Record<string, string>> = {
    Génesis: 'huichol/hch_GEN_capitulos_versiculos.json',
    Éxodo: 'huichol/hch_EXO_capitulos_versiculos.json',
    Levítico: 'huichol/hch_LEV_capitulos_versiculos.json',
    Números: 'huichol/hch_NUM_capitulos_versiculos.json',
    Deuteronomio: 'huichol/hch_DEU_capitulos_versiculos.json',
    Josué: 'huichol/hch_JOS_capitulos_versiculos.json',
    Jueces: 'huichol/hch_JDG_capitulos_versiculos.json',
    Rut: 'huichol/hch_RUT_capitulos_versiculos.json',
    '1 Samuel': 'huichol/hch_1SA_capitulos_versiculos.json',
    '2 Samuel': 'huichol/hch_2SA_capitulos_versiculos.json',
    '1 Reyes': 'huichol/hch_1KI_capitulos_versiculos.json',
    '2 Reyes': 'huichol/hch_2KI_capitulos_versiculos.json',
    '1 Crónicas': 'huichol/hch_1CH_capitulos_versiculos.json',
    '2 Crónicas': 'huichol/hch_2CH_capitulos_versiculos.json',
    Esdras: 'huichol/hch_EZR_capitulos_versiculos.json',
    Nehemías: 'huichol/hch_NEH_capitulos_versiculos.json',
    Ester: 'huichol/hch_EST_capitulos_versiculos.json',
    Job: 'huichol/hch_JOB_capitulos_versiculos.json',
    Salmos: 'huichol/hch_PSA_capitulos_versiculos.json',
    Proverbios: 'huichol/hch_PRO_capitulos_versiculos.json',
    Eclesiastés: 'huichol/hch_ECC_capitulos_versiculos.json',
    Cantares: 'huichol/hch_SNG_capitulos_versiculos.json',
    Isaías: 'huichol/hch_ISA_capitulos_versiculos.json',
    Jeremías: 'huichol/hch_JER_capitulos_versiculos.json',
    Lamentaciones: 'huichol/hch_LAM_capitulos_versiculos.json',
    Ezequiel: 'huichol/hch_EZK_capitulos_versiculos.json',
    Daniel: 'huichol/hch_DAN_capitulos_versiculos.json',
    Oseas: 'huichol/hch_HOS_capitulos_versiculos.json',
    Joel: 'huichol/hch_JOL_capitulos_versiculos.json',
    Amós: 'huichol/hch_AMO_capitulos_versiculos.json',
    Abdías: 'huichol/hch_OBA_capitulos_versiculos.json',
    Jonás: 'huichol/hch_JON_capitulos_versiculos.json',
    Miqueas: 'huichol/hch_MIC_capitulos_versiculos.json',
    Nahúm: 'huichol/hch_NAM_capitulos_versiculos.json',
    Habacuc: 'huichol/hch_HAB_capitulos_versiculos.json',
    Sofonías: 'huichol/hch_ZEP_capitulos_versiculos.json',
    Hageo: 'huichol/hch_HAG_capitulos_versiculos.json',
    Zacarías: 'huichol/hch_ZEC_capitulos_versiculos.json',
    Malaquías: 'huichol/hch_MAL_capitulos_versiculos.json',
    Mateo: 'huichol/hchNT_MAT_capitulos_versiculos.json',
    Marcos: 'huichol/hch_MRK_capitulos_versiculos.json',
    Lucas: 'huichol/hch_LUK_capitulos_versiculos.json',
    Juan: 'huichol/hch_JHN_capitulos_versiculos.json',
    Hechos: 'huichol/hch_ACT_capitulos_versiculos.json',
    Romanos: 'huichol/hch_ROM_capitulos_versiculos.json',
    '1 Corintios': 'huichol/hch_1CO_capitulos_versiculos.json',
    '2 Corintios': 'huichol/hch_2CO_capitulos_versiculos.json',
    Gálatas: 'huichol/hch_GAL_capitulos_versiculos.json',
    Efesios: 'huichol/hch_EPH_capitulos_versiculos.json',
    Filipenses: 'huichol/hch_PHP_capitulos_versiculos.json',
    Colosenses: 'huichol/hch_COL_capitulos_versiculos.json',
    '1 Tesalonicenses': 'huichol/hch_1TH_capitulos_versiculos.json',
    '2 Tesalonicenses': 'huichol/hch_2TH_capitulos_versiculos.json',
    '1 Timoteo': 'huichol/hch_1TI_capitulos_versiculos.json',
    '2 Timoteo': 'huichol/hch_2TI_capitulos_versiculos.json',
    Tito: 'huichol/hch_TIT_capitulos_versiculos.json',
    Filemón: 'huichol/hch_PHM_capitulos_versiculos.json',
    Hebreos: 'huichol/hch_HEB_capitulos_versiculos.json',
    Santiago: 'huichol/hch_JAS_capitulos_versiculos.json',
    '1 Pedro': 'huichol/hch_1PE_capitulos_versiculos.json',
    '2 Pedro': 'huichol/hch_2PE_capitulos_versiculos.json',
    '1 Juan': 'huichol/hch_1JN_capitulos_versiculos.json',
    '2 Juan': 'huichol/hch_2JN_capitulos_versiculos.json',
    '3 Juan': 'huichol/hch_3JN_capitulos_versiculos.json',
    Judas: 'huichol/hch_JUD_capitulos_versiculos.json',
    Apocalipsis: 'huichol/hch_REV_capitulos_versiculos.json',
};

export function getHuicholJsonPathForSpanishBook(bookName: string): string | null {
    return HUICHOL_SPANISH_BOOK_TO_JSON[bookName] ?? null;
}
