/**
 * Clave de libro en `bibleData` / `loadFullBibleLookup` (nombre UBS en minúsculas, español).
 * Debe coincidir con `es_rvr_1960.json` (p. ej. "s. mateo", "génesis").
 */
const USFM_TO_SPANISH_KEY: Record<string, string> = {
  GEN: 'génesis',
  EXO: 'éxodo',
  LEV: 'levítico',
  NUM: 'números',
  DEU: 'deuteronomio',
  JOS: 'josué',
  JDG: 'jueces',
  RUT: 'rut',
  '1SA': '1 samuel',
  '2SA': '2 samuel',
  '1KI': '1 reyes',
  '2KI': '2 reyes',
  '1CH': '1 crónicas',
  '2CH': '2 crónicas',
  EZR: 'esdras',
  NEH: 'nehemías',
  EST: 'ester',
  JOB: 'job',
  PSA: 'salmos',
  PRO: 'proverbios',
  ECC: 'eclesiastés',
  SNG: 'cantares',
  ISA: 'isaías',
  JER: 'jeremías',
  LAM: 'lamentaciones',
  EZK: 'ezequiel',
  DAN: 'daniel',
  HOS: 'oseas',
  JOL: 'joel',
  AMO: 'amós',
  OBA: 'abdías',
  JON: 'jonás',
  MIC: 'miqueas',
  NAM: 'nahúm',
  HAB: 'habacuc',
  ZEP: 'sofonías',
  HAG: 'hageo',
  ZEC: 'zacarías',
  MAL: 'malaquías',
  MAT: 's. mateo',
  MRK: 's. marcos',
  LUK: 's. lucas',
  JHN: 's. juan',
  ACT: 'hechos',
  ROM: 'romanos',
  '1CO': '1 corintios',
  '2CO': '2 corintios',
  GAL: 'gálatas',
  EPH: 'efesios',
  PHP: 'filipenses',
  COL: 'colosenses',
  '1TH': '1 tesalonicenses',
  '2TH': '2 tesalonicenses',
  '1TI': '1 timoteo',
  '2TI': '2 timoteo',
  TIT: 'tito',
  PHM: 'filemón',
  HEB: 'hebreos',
  JAS: 'santiago',
  '1PE': '1 pedro',
  '2PE': '2 pedro',
  '1JN': '1 juan',
  '2JN': '2 juan',
  '3JN': '3 juan',
  JUD: 'judas',
  REV: 'apocalipsis',
};

export function usfmToSpanishBibleDataKey(usfm: string): string | null {
  const k = USFM_TO_SPANISH_KEY[usfm.toUpperCase()];
  return k ?? null;
}
