import { amor } from './reading-plan-data/amor';
import { ansiedad } from './reading-plan-data/ansiedad';
import { enojo } from './reading-plan-data/enojo';
import { sanidad } from './reading-plan-data/sanidad';
import { territorioDeFe } from './reading-plan-data/territorio-de-fe';
import { palabraDeDios } from './reading-plan-data/palabra-de-dios';
import { mentirasCreibles } from './reading-plan-data/mentiras-creibles';
import { desdeElPrincipioHastaElAmenMarzo } from './reading-plan-data/desde-el-principio-hasta-el-amen-marzo';
import { discipulado } from './reading-plan-data/discipulado';
import { cuaresma2026 } from './reading-plan-data/cuaresma-2026-mateo-y-salmos';
import { elEvangelioDeIsaias } from './reading-plan-data/el-evangelio-de-isaias';
import { isaiasEsforzandoseMenos } from './reading-plan-data/isaias-esforzandose-menos';
import { leeYAbsorbeIsaiasEnCincoDias } from './reading-plan-data/lee-y-absorbe-isaias-en-cinco-dias';
import { esperanza } from './reading-plan-data/esperanza';
// This file will store the data for all reading plans.
import {bookOrder, chaptersInBook} from './bible-data';

const generateClassicPlan = () => {
    const otBooks = bookOrder.slice(0, 39);
    const ntBooks = bookOrder.slice(39);

    let otChapter = 1;
    let otBookIndex = 0;
    let ntChapter = 1;
    let ntBookIndex = 0;

    const plan = [];

    for (let day = 1; day <= 365; day++) {
        const readings = [];

        // OT Reading
        if (otBookIndex < otBooks.length) {
            const currentBook = otBooks[otBookIndex];
            readings.push(`${currentBook} ${otChapter}`);
            otChapter++;
            if (otChapter > chaptersInBook(currentBook)) {
                otBookIndex++;
                otChapter = 1;
            }
        }
        
        // NT Reading
        if (ntBookIndex < ntBooks.length) {
            const currentBook = ntBooks[ntBookIndex];
            readings.push(`${currentBook} ${ntChapter}`);
            ntChapter++;
            if (ntChapter > chaptersInBook(currentBook)) {
                ntBookIndex++;
                ntChapter = 1;
            }
        } else { // Loop NT if OT is not finished
            ntBookIndex = 0;
            ntChapter = 1;
            const currentBook = ntBooks[ntBookIndex];
            readings.push(`${currentBook} ${ntChapter}`);
            ntChapter++;
        }

        plan.push({
            day,
            reading: readings.join('; '),
            summary: `Lectura del día ${day} del plan anual.`
        });
    }
    return plan;
};

export const allPlanData: { [key: string]: any[] } = {
    'amor': amor,
    'ansiedad': ansiedad,
    'enojo': enojo,
    'sanidad': sanidad,
    'territorio-de-fe': territorioDeFe,
    'palabra-de-dios': palabraDeDios,
    'mentiras-creibles': mentirasCreibles,
    'desde-el-principio-hasta-el-amen-marzo': desdeElPrincipioHastaElAmenMarzo,
    'discipulado': discipulado,
    'cuaresma-2026-mateo-y-salmos': cuaresma2026,
    'el-evangelio-de-isaias': elEvangelioDeIsaias,
    'isaias-esforzandose-menos': isaiasEsforzandoseMenos,
    'lee-y-absorbe-isaias-en-cinco-dias': leeYAbsorbeIsaiasEnCincoDias,
    'esperanza': esperanza,
    'proverbios-sabiduria-diaria': Array.from({ length: 31 }, (_, i) => ({
        day: i + 1,
        reading: `Proverbios ${i + 1}`,
        summary: `Un capítulo de sabiduría para guiar tu día, abordando temas de justicia, prudencia y vida recta. El capítulo ${i + 1} ofrece consejos prácticos para las relaciones, el trabajo y la integridad personal.`,
    })),
    'viaje-a-traves-de-juan': [
        { day: 1, reading: 'Juan 1:1-18', summary: `Contempla al Verbo eterno: aquí se revela la preexistencia, la divinidad y la encarnación del Hijo. Medita en cómo la Palabra se hizo carne para habitar entre nosotros; deja que este asombro te conduzca a la adoración y a una vida transformada por la presencia de Dios.` },
        { day: 2, reading: 'Juan 1:19-34', summary: `Reflexiona en el ministerio de Juan el Bautista como testigo que apunta a Cristo. Ora por un corazón humilde que reconozca la superioridad de Jesús, que no busque su propio protagonismo sino señalar al Cordero que quita el pecado del mundo.` },
        { day: 3, reading: 'Juan 1:35-51', summary: `Acompaña a los primeros discípulos en su llamado personal por Jesús. Pide la gracia de una fe que responde al encuentro: que tu llamado no se quede en curiosidad sino que te lleve a seguir con fidelidad y a invitar a otros a ver al Señor.` },
        { day: 4, reading: 'Juan 2', summary: `Medita en las primeras señales de Jesús: el milagro en Caná que manifiesta su gloria y la purificación del templo que revela su celo por la verdadera adoración. Ora para que Jesús transforme tanto tu celebración como tu reverencia hacia Él.` },
        { day: 5, reading: 'Juan 3:1-21', summary: `Acércate a la enseñanza sobre nacer de nuevo: una obra del Espíritu que inaugura una vida nueva en Cristo. Pide ser renovado por la gracia, entender la profundidad del amor del Padre y vivir con la certeza de la vida eterna.` },
        { day: 6, reading: 'Juan 3:22-36', summary: `Escucha el llamado a regocijarte cuando Cristo crece y disminuir tú mismo. Ora por humildad para aceptar la autoridad de Jesús y por confianza en la obra redentora que trasciende el reconocimiento humano.` },
        { day: 7, reading: 'Juan 4:1-42', summary: `Encuentra a Jesús junto al pozo: su oferta de agua viva satisface la sed del alma. Medita en el alcance universal del evangelio y en la compasión del Señor que busca a los sedientos; pide valentía para ser testigo en ámbitos inesperados.` },
        { day: 8, reading: 'Juan 4:43-54', summary: `Contempla la fe del funcionario real: la palabra de Jesús trae vida aún a distancia. Ora por confianza en la autoridad de Cristo sobre la enfermedad y por serenidad para dejar en sus manos aquello que te preocupa.` },
        { day: 9, reading: 'Juan 5:1-23', summary: `Observa la compasión que da vida y la autoridad de Jesús frente a la ley y las tradiciones. Pide al Señor que tu fe reconozca su voz y obedezca su iniciativa liberadora, confiando en su poder para restaurar.` },
        { day: 10, reading: 'Juan 5:24-47', summary: `Escucha las razones que Jesús da para su autoridad: el testimonio del Padre, las Escrituras y su obra. Ora por discernimiento para creer en su testimonio y por valentía para vivir conforme a la verdad que salva.` },
        { day: 11, reading: 'Juan 6:1-21', summary: `Acepta al Señor como proveedor y Salvador: el pan que multiplica anuncia su suficiencia. Medita también en la paz que trae al andar sobre la tormenta; pide coraje para confiar en su provisión y presencia.` },
        { day: 12, reading: 'Juan 6:22-40', summary: `Profundiza en la enseñanza del Pan de Vida: creer en Jesús es recibir vida eterna. Ora para que tu dependencia sea diaria y que el Señor alimente tu alma con su verdad perdurable.` },
        { day: 13, reading: 'Juan 6:41-71', summary: `Cuando la doctrina resulta exigente, examina tu fe: ¿te sostienes en Cristo? Pide fidelidad para permanecer en el Señor aun cuando las palabras sean difíciles, y confía en que su revelación requiere respuesta comprometida.` },
        { day: 14, reading: 'Juan 7:1-31', summary: `Escucha a Jesús enseñando en medio de la división: su palabra rompe esquemas y convoca a la obediencia. Ora por oídos que distingan su voz en la confusión y por entrega que convierta la doctrina en vida.` },
        { day: 15, reading: 'Juan 7:32-52', summary: `Mira cómo la llegada de la verdad provoca reacciones diversas. Pide a Dios sabiduría para testificar con mansedumbre y claridad, y por el Espíritu que confirme la verdad en los corazones.` },
        { day: 16, reading: 'Juan 8:1-30', summary: `Fíjate en la gracia que corrige y la verdad que libera: Jesús confronta y restaura. Ora por humildad que reconozca la necesidad de perdón y por valentía para vivir en la libertad que Él ofrece.` },
        { day: 17, reading: 'Juan 8:31-59', summary: `Medita en la afirmación de Jesús sobre la libertad que brota de la verdad. Pide al Señor que su palabra te arraigue, rompa las cadenas del pecado y te sostenga en una fidelidad que honra al Padre.` },
        { day: 18, reading: 'Juan 9', summary: `Observa cómo Jesús abre ojos: una obra física que simboliza la revelación espiritual. Ora por visión para reconocer a Cristo y por valor para confesar públicamente el testimonio de su obra.` },
        { day: 19, reading: 'Juan 10:1-21', summary: `Escucha la imagen del Buen Pastor que da su vida por las ovejas: amor sacrificial y cuidado cercano. Pide seguridad en su guía y sensibilidad para seguir su voz día a día.` },
        { day: 20, reading: 'Juan 10:22-42', summary: `Contempla la unidad del Padre y del Hijo revelada en palabra y obra: fuente de confianza cristiana. Ora para que esa unidad te fortalezca en la fe y te impulse a la adoración y al testimonio.` },
        { day: 21, reading: 'Juan 11:1-44', summary: `Permanece con Jesús en el duelo de la muerte de Lázaro y contempla su poder sobre la muerte. Pide consuelo en la pérdida y fortaleza para creer en la esperanza que la resurrección anuncia.` },
        { day: 22, reading: 'Juan 11:45-57', summary: `Siente la tensión entre reacción humana y propósito divino: la oposición no anula el plan redentor. Ora por firmeza para sostener la verdad frente a la presión y por sabiduría para actuar según la voluntad de Dios.` },
        { day: 23, reading: 'Juan 12:1-19', summary: `Adora con María y contempla la apertura del camino hacia la pasión: entrega que honra al Mesías. Reflexiona en lo que significa honrar a Jesús con lo mejor de tu vida y pide un corazón que adore sacrificialmente.` },
        { day: 24, reading: 'Juan 12:20-50', summary: `Recibe la palabra que anuncia la finalidad de la entrega de Cristo: creer en la luz que trae vida. Pide claridad para aceptar su llamado y valor para vivir conforme a la palabra que ilumina.` },
        { day: 25, reading: 'Juan 13', summary: `Permanece en el ejemplo de servicio en la Última Cena: amor humilde y entrega total. Ora por un corazón dispuesto a servir, perdonar y amar como Jesús lo hizo, poniendo a los demás por delante.` },
        { day: 26, reading: 'Juan 14', summary: `Confía en las promesas de consuelo y en la morada preparada por el Hijo: esperanza segura. Pide al Espíritu que haga tangible esa promesa en tu vida y que te guíe en verdad y paz.` },
        { day: 27, reading: 'Juan 15', summary: `Quédate en la vid para recibir vida fructífera: comunión que produce fruto para la gloria de Dios. Ora por permanencia íntima con Cristo y por frutos que demuestren su vida en ti.` },
        { day: 28, reading: 'Juan 16', summary: `Busca la guía y el consuelo del Espíritu en medio del juicio y la prueba. Confía en que la tristeza dará paso al gozo porque el Consolador obra en ti para sostener, enseñar y glorificar a Cristo.` },
        { day: 29, reading: 'Juan 17', summary: `Únete a la oración sacerdotal de Jesús por unidad y santidad: una petición por su pueblo. Medita en su intercesión y pide por unidad, santificación y testimonio que honre al Padre.` },
        { day: 30, reading: 'Juan 18', summary: `Sigue a Jesús en su camino hacia la pasión: presencia, traición y juicio que culminan en la redención. Mantén la mirada en su fidelidad y pide valor para ser testigo fiel aun en la adversidad.` },
    ],
    'la-historia-de-la-redencion': [
        { day: 1, reading: 'Génesis 1-3', summary: 'La creación del mundo y la caída del hombre.' },
        { day: 2, reading: 'Génesis 12:1-9; 15:1-6', summary: 'El llamado de Abram y el pacto de Dios con él.' },
        { day: 3, reading: 'Éxodo 12, 13, 14', summary: 'La Pascua y el cruce del Mar Rojo.' },
        { day: 4, reading: 'Éxodo 19-20', summary: 'Dios entrega los Diez Mandamientos en el Monte Sinaí.' },
        { day: 5, reading: 'Levítico 16', summary: 'Instrucciones para el Día de la Expiación.' },
        { day: 6, reading: 'Números 13-14', summary: 'Los espías exploran Canaán y la rebelión de Israel.' },
        { day: 7, reading: 'Deuteronomio 6; 30:11-20', summary: 'El gran mandamiento de amar a Dios y la elección entre la vida y la muerte.' },
        { day: 8, reading: 'Josué 1; 24', summary: 'Josué lidera a Israel y el pueblo renueva el pacto.' },
        { day: 9, reading: 'Jueces 2:6-23; 6-7', summary: 'El ciclo de desobediencia de Israel y la historia de Gedeón.' },
        { day: 10, reading: '1 Samuel 16-17', summary: 'David es ungido rey y derrota a Goliat.' },
        { day: 11, reading: '2 Samuel 7; 11-12', summary: 'El pacto de Dios con David y su pecado con Betsabé.' },
        { day: 12, reading: '1 Reyes 8; 18', summary: 'La dedicación del templo de Salomón y el enfrentamiento de Elías con los profetas de Baal.' },
        { day: 13, reading: '2 Reyes 17; 25', summary: 'La caída de Israel y Judá.' },
        { day: 14, reading: 'Job 1-2; 42', summary: 'El sufrimiento de Job y su restauración.' },
        { day: 15, reading: 'Salmos 1; 23; 51', summary: 'Poemas de sabiduría, confianza y arrepentimiento.' },
        { day: 16, reading: 'Proverbios 1-3', summary: 'La búsqueda de la sabiduría.' },
        { day: 17, reading: 'Isaías 1; 9:1-7', summary: 'Un llamado al arrepentimiento y la profecía del nacimiento de un niño que será Rey.' },
        { day: 18, reading: 'Isaías 52:13-53:12', summary: 'La profecía del Siervo Sufriente.' },
        { day: 19, reading: 'Jeremías 1; 31:31-34', summary: 'El llamado de Jeremías y la promesa de un nuevo pacto.' },
        { day: 20, reading: 'Ezequiel 36:22-38; 37', summary: 'La promesa de un corazón nuevo y el valle de los huesos secos.' },
        { day: 21, reading: 'Daniel 7-9', summary: 'Las visiones de Daniel y su oración por su pueblo.' },
        { day: 22, reading: 'Mateo 1-2; Lucas 1-2', summary: 'El nacimiento de Jesús.' },
        { day: 23, reading: 'Mateo 5-7', summary: 'El Sermón del Monte.' },
        { day: 24, reading: 'Juan 1-3', summary: 'El Verbo se hizo carne y la conversación de Jesús con Nicodemo.' },
        { day: 25, reading: 'Romanos 3-5', summary: 'La justificación por la fe.' },
        { day: 26, reading: 'Romanos 8', summary: 'La vida en el Espíritu.' },
        { day: 27, reading: 'Gálatas 5', summary: 'La libertad en Cristo y el fruto del Espíritu.' },
        { day: 28, reading: 'Efesios 1-2', summary: 'Las bendiciones espirituales en Cristo y la salvación por gracia.' },
        { day: 29, reading: 'Hebreos 11-12', summary: 'La fe y la perseverancia.' },
        { day: 30, reading: 'Apocalipsis 1; 21-22', summary: 'La visión de Juan y la promesa de un cielo nuevo y una tierra nueva.' },
    ],
    'biblia-en-un-ano-clasico': generateClassicPlan(),
    'plan-cronologico': [
        { day: 1, reading: 'Génesis 1;2;3;', summary: 'Orígenes' },
        { day: 2, reading: 'Génesis 4;5;6;7;', summary: 'Orígenes' },
        { day: 3, reading: 'Génesis 8;9;10;11;', summary: 'Orígenes' },
        { day: 4, reading: 'Job 1;2;3;4;', summary: 'Orígenes' },
        { day: 5, reading: 'Job 5;6;7;8;9;', summary: 'Orígenes' },
        { day: 6, reading: 'Job 10;11;12;13;', summary: 'Orígenes' },
        { day: 7, reading: 'Job 14;15;16;17;', summary: 'Orígenes' },
        { day: 8, reading: 'Job 18;19;20;21;', summary: 'Orígenes' },
        { day: 9, reading: 'Job 22;23;24;25;26;', summary: 'Orígenes' },
        { day: 10, reading: 'Job 27;28;29;30;31;', summary: 'Orígenes' },
        { day: 11, reading: 'Job 32;33;34;35;36;37', summary: 'Orígenes' },
        { day: 12, reading: 'Job 38;39;', summary: 'Continuación de Job' },
        { day: 13, reading: 'Job 40;41;42;', summary: 'Continuación de Job' },
        { day: 14, reading: 'Génesis 12;13;14;15;', summary: 'Continuación de Job' },
        { day: 15, reading: 'Génesis 16;17;18;', summary: 'Continuación de Job' },
        { day: 16, reading: 'Génesis 19;20;21;', summary: 'Continuación de Job' },
        { day: 17, reading: 'Génesis 22;23;24;', summary: 'Continuación de Job' },
        { day: 18, reading: 'Génesis 25;26;', summary: 'Continuación de Job' },
        { day: 19, reading: 'Génesis 27;28;29;', summary: 'Continuación de Job' },
        { day: 20, reading: 'Génesis 30;31;32;', summary: 'Continuación de Job' },
        { day: 21, reading: 'Génesis 33;34;35;36;', summary: 'Continuación de Job' },
        { day: 22, reading: 'Génesis 37;38;39;', summary: 'Patriarcas' },
        { day: 23, reading: 'Génesis 40;41;42;', summary: 'Patriarcas' },
        { day: 24, reading: 'Génesis 43;44;45;', summary: 'Patriarcas' },
        { day: 25, reading: 'Génesis 46;47;48;', summary: 'Patriarcas' },
        { day: 26, reading: 'Génesis 49;50;', summary: 'Patriarcas' },
        { day: 27, reading: 'Éxodo 1;2;3;4;', summary: 'Patriarcas' },
        { day: 28, reading: 'Éxodo 5;6;7;', summary: 'Patriarcas' },
        { day: 29, reading: 'Éxodo 8;9;10;', summary: 'Patriarcas' },
        { day: 30, reading: 'Éxodo 11;12;13;', summary: 'Patriarcas' },
        { day: 31, reading: 'Éxodo 14;15;16;', summary: 'Patriarcas' },
        { day: 32, reading: 'Éxodo 17;18;19;20;', summary: 'Patriarcas' },
        { day: 33, reading: 'Éxodo 21;22;23;', summary: 'Patriarcas' },
        { day: 34, reading: 'Éxodo 24;25;26;27;', summary: 'Patriarcas' },
        { day: 35, reading: 'Éxodo 28;29;30;31;', summary: 'Patriarcas' },
        { day: 36, reading: 'Éxodo 32;33;34;', summary: 'Patriarcas' },
        { day: 37, reading: 'Éxodo 35;36;37;', summary: 'Ley y tabernáculo' },
        { day: 38, reading: 'Éxodo 38;39;40;', summary: 'Ley y tabernáculo' },
        { day: 39, reading: 'Levítico 1;2;3;4;', summary: 'Ley y tabernáculo' },
        { day: 40, reading: 'Levítico 5;6;7;', summary: 'Ley y tabernáculo' },
        { day: 41, reading: 'Levítico 8;9;10;', summary: 'Ley y tabernáculo' },
        { day: 42, reading: 'Levítico 11;12;13;', summary: 'Ley y tabernáculo' },
        { day: 43, reading: 'Levítico 14;15;', summary: 'Ley y tabernáculo' },
        { day: 44, reading: 'Levítico 16;17;18;', summary: 'Ley y tabernáculo' },
        { day: 45, reading: 'Levítico 19;20;21;', summary: 'Ley y tabernáculo' },
        { day: 46, reading: 'Levítico 22;23;', summary: 'Ley y tabernáculo' },
        { day: 47, reading: 'Levítico 24;25;', summary: 'Ley y tabernáculo' },
        { day: 48, reading: 'Levítico 26;27;', summary: 'Ley y tabernáculo' },
        { day: 49, reading: 'Números 1;2;', summary: 'Ley y tabernáculo' },
        { day: 50, reading: 'Números 3;4;', summary: 'Ley y tabernáculo' },
        { day: 51, reading: 'Números 5;6;', summary: 'Ley y tabernáculo' },
        { day: 52, reading: 'Números 7', summary: 'Ley y tabernáculo' },
        { day: 53, reading: 'Números 8;9;10;', summary: 'Ley y tabernáculo' },
        { day: 54, reading: 'Números 11;12;13;', summary: 'Ley y tabernáculo' },
        { day: 55, reading: 'Números 14;15; Salmos 90', summary: 'Desde el desierto hasta Moab' },
        { day: 56, reading: 'Números 16;17;', summary: 'Desde el desierto hasta Moab' },
        { day: 57, reading: 'Números 18;19;20;', summary: 'Desde el desierto hasta Moab' },
        { day: 58, reading: 'Números 21;22;', summary: 'Desde el desierto hasta Moab' },
        { day: 59, reading: 'Números 23;24;25;', summary: 'Desde el desierto hasta Moab' },
        { day: 60, reading: 'Números 26;27;', summary: 'Desde el desierto hasta Moab' },
        { day: 61, reading: 'Números 28;29;30;', summary: 'Desde el desierto hasta Moab' },
        { day: 62, reading: 'Números 31;32;', summary: 'Desde el desierto hasta Moab' },
        { day: 63, reading: 'Números 33;34;', summary: 'Desde el desierto hasta Moab' },
        { day: 64, reading: 'Números 35;36;', summary: 'Desde el desierto hasta Moab' },
        { day: 65, reading: 'Deuteronomio 1;2;', summary: 'Desde el desierto hasta Moab' },
        { day: 66, reading: 'Deuteronomio 3;4;', summary: 'Desde el desierto hasta Moab' },
        { day: 67, reading: 'Deuteronomio 5;6;7;', summary: 'Desde el desierto hasta Moab' },
        { day: 68, reading: 'Deuteronomio 8;9;10;', summary: 'Desde el desierto hasta Moab' },
        { day: 69, reading: 'Deuteronomio 11;12;13;', summary: 'Desde el desierto hasta Moab' },
        { day: 70, reading: 'Deuteronomio 14;15;16;', summary: 'Desde el desierto hasta Moab' },
        { day: 71, reading: 'Deuteronomio 17;18;19;20;', summary: 'Desde el desierto hasta Moab' },
        { day: 72, reading: 'Deuteronomio 21;22;23;', summary: 'Desde el desierto hasta Moab' },
        { day: 73, reading: 'Deuteronomio 24;25;26;27;', summary: 'Desde el desierto hasta Moab' },
        { day: 74, reading: 'Deuteronomio 28;29;', summary: 'Final de Moisés' },
        { day: 75, reading: 'Deuteronomio 30;31;', summary: 'Final de Moisés' },
        { day: 76, reading: 'Deuteronomio 32;33;34;', summary: 'Final de Moisés' },
        { day: 77, reading: 'Josué 1;2;3;4;', summary: 'Final de Moisés' },
        { day: 78, reading: 'Josué 5;6;7;8;', summary: 'Final de Moisés' },
        { day: 79, reading: 'Josué 9;10;11;', summary: 'Final de Moisés' },
        { day: 80, reading: 'Josué 12;13;14;15;', summary: 'Final de Moisés' },
        { day: 81, reading: 'Josué 16;17;18;', summary: 'Final de Moisés' },
        { day: 82, reading: 'Josué 19;20;21;', summary: 'Final de Moisés' },
        { day: 83, reading: 'Josué 22;23;24;', summary: 'Final de Moisés' },
        { day: 84, reading: 'Jueces 1;2;3;', summary: 'Final de Moisés' },
        { day: 85, reading: 'Jueces 4;5;', summary: 'Jueces, Rut y Samuel' },
        { day: 86, reading: 'Jueces 6;7;', summary: 'Jueces, Rut y Samuel' },
        { day: 87, reading: 'Jueces 8;9;', summary: 'Jueces, Rut y Samuel' },
        { day: 88, reading: 'Jueces 10;11;12;', summary: 'Jueces, Rut y Samuel' },
        { day: 89, reading: 'Jueces 13;14;15;', summary: 'Jueces, Rut y Samuel' },
        { day: 90, reading: 'Jueces 16;17;18;', summary: 'Jueces, Rut y Samuel' },
        { day: 91, reading: 'Jueces 19;20;21;', summary: 'Jueces, Rut y Samuel' },
        { day: 92, reading: 'Rut 1;2;3;4;', summary: 'Jueces, Rut y Samuel' },
        { day: 93, reading: '1 Samuel 1;2;3;', summary: 'Jueces, Rut y Samuel' },
        { day: 94, reading: '1 Samuel 4;5;6;7;', summary: 'Jueces, Rut y Samuel' },
        { day: 95, reading: '1 Samuel 8;9;10;', summary: 'Jueces, Rut y Samuel' },
        { day: 96, reading: '1 Samuel 11;12;13;', summary: 'Jueces, Rut y Samuel' },
        { day: 97, reading: '1 Samuel 14;15;', summary: 'Jueces, Rut y Samuel' },
        { day: 98, reading: '1 Samuel 16;17;', summary: 'Jueces, Rut y Samuel' },
        { day: 99, reading: '1 Samuel 18;19;20; Salmos 11, 59', summary: 'Jueces, Rut y Samuel' },
        { day: 100, reading: '1 Samuel 21;22;23;24;', summary: 'Jueces, Rut y Samuel' },
        { day: 101, reading: 'Salmos 7, 27, 31, 34, 52', summary: 'Jueces, Rut y Samuel' },
        { day: 102, reading: '1 Samuel 25, 26, 27', summary: 'Jueces, Rut y Samuel' },
        { day: 103, reading: 'Salmos 17, 35, 54, 63', summary: 'Jueces, Rut y Samuel' },
        { day: 104, reading: '1 Samuel 28, 29, 30, 31', summary: 'Jueces, Rut y Samuel' },
        { day: 105, reading: '2 Samuel 1, 2,3', summary: 'Jueces, Rut y Samuel' },
        { day: 106, reading: '2 Samuel 4, 5, 6, 7', summary: 'Jueces, Rut y Samuel' },
        { day: 107, reading: '2 Samuel 8, 9, 10, 11, 12', summary: 'Jueces, Rut y Samuel' },
        { day: 108, reading: 'Salmos 51, 32, 86, 122', summary: 'Jueces, Rut y Samuel' },
        { day: 109, reading: '2 Samuel 13, 14, 15', summary: 'Jueces, Rut y Samuel' },
        { day: 110, reading: 'Salmos 3, 4, 12, 13, 28, 55', summary: 'Jueces, Rut y Samuel' },
        { day: 111, reading: '2 Samuel 16, 17, 18', summary: 'Reino de David y Salomón' },
        { day: 112, reading: 'Salmos 26, 40, 58, 61, 62, 64', summary: 'Reino de David y Salomón' },
        { day: 113, reading: '2 Samuel 19, 20, 21', summary: 'Reino de David y Salomón' },
        { day: 114, reading: 'Salmos 5, 38, 41, 42', summary: 'Reino de David y Salomón' },
        { day: 115, reading: '2 Samuel 22, 23, 24', summary: 'Reino de David y Salomón' },
        { day: 116, reading: 'Salmos 95, 96, 97, 98, 99, 100', summary: 'Reino de David y Salomón' },
        { day: 117, reading: '1 Crónicas 1, 2', summary: 'Reino de David y Salomón' },
        { day: 118, reading: '1 Crónicas 3, 4, 5', summary: 'Reino de David y Salomón' },
        { day: 119, reading: '1 Crónicas 6', summary: 'Reino de David y Salomón' },
        { day: 120, reading: '1 Crónicas 7, 8, 9, 10', summary: 'Reino de David y Salomón' },
        { day: 121, reading: '1 Crónicas 11, 12', summary: 'Reino de David y Salomón' },
        { day: 122, reading: '1 Crónicas 13, 14, , 15, 16', summary: 'Reino de David y Salomón' },
        { day: 123, reading: 'Salmos 96, 105, 106', summary: 'Reino de David y Salomón' },
        { day: 124, reading: '1 Crónicas 17, 18, 19, 20', summary: 'Reino de David y Salomón' },
        { day: 125, reading: '1 Crónicas 21, 22, 23', summary: 'Reino de David y Salomón' },
        { day: 126, reading: '1 Crónicas 24, 25, 26', summary: 'Reino de David y Salomón' },
        { day: 127, reading: '1 Crónicas 27, 28, 29', summary: 'Reino de David y Salomón' },
        { day: 128, reading: '1 Reyes 1, 2', summary: 'Reino de David y Salomón' },
        { day: 129, reading: '1 Reyes 3, 4', summary: 'Reino de David y Salomón' },
        { day: 130, reading: '1 Reyes 5, 6, 7', summary: 'Reino de David y Salomón' },
        { day: 131, reading: '1 Reyes 8, 9', summary: 'Reino de David y Salomón' },
        { day: 132, reading: '1 Reyes 10, 11; 2 Crónicas 1, 2, 3, 4, 5, 6, 7, 8, 9', summary: 'Reino de David y Salomón' },
        { day: 133, reading: 'Proverbios 1, 2, 3', summary: 'Reino de David y Salomón' },
        { day: 134, reading: 'Proverbios 4, 5, 6', summary: 'Reino de David y Salomón' },
        { day: 135, reading: 'Proverbios 7, 8, 9', summary: 'Reino de David y Salomón' },
        { day: 136, reading: 'Proverbios 10, 11, 12', summary: 'Reino de David y Salomón' },
        { day: 137, reading: 'Proverbios 13, 14, 15', summary: 'Reino de David y Salomón' },
        { day: 138, reading: 'Proverbios 16, 17, 18', summary: 'Reino de David y Salomón' },
        { day: 139, reading: 'Proverbios 19, 20, 21', summary: 'Reino de David y Salomón' },
        { day: 140, reading: 'Proverbios 22, 23, 24', summary: 'Reino de David y Salomón' },
        { day: 141, reading: 'Proverbios 25, 26, 27', summary: 'Reino de David y Salomón' },
        { day: 142, reading: 'Proverbios 28, 29, 20, 31', summary: 'Reino de David y Salomón' },
        { day: 143, reading: 'Eclesiastés 1, 2, 3, 4, 5, 6', summary: 'Reino de David y Salomón' },
        { day: 144, reading: 'Eclesiastés 7, 8, 9, 10, 11, 12', summary: 'Reino de David y Salomón' },
        { day: 145, reading: 'Cantar de los Cantares 1, 2, 3, 4, 5, 6, 7, 8', summary: 'Reino de David y Salomón' },
        { day: 146, reading: '1 Reyes 12, 13, 14', summary: 'Reino de David y Salomón' },
        { day: 147, reading: '1 Reyes 15, 16, 17', summary: 'Reino de David y Salomón' },
        { day: 148, reading: '1 Reyes 18, 19, 20', summary: 'Reino de David y Salomón' },
        { day: 149, reading: '1 Reyes 21, 22', summary: 'Reino de David y Salomón' },
        { day: 150, reading: '2 Reyes 1, 2, 3', summary: 'Reino de David y Salomón' },
        { day: 151, reading: '2 Reyes 4, 5, 6, 7', summary: 'Reyes, Profetas y Exilio' },
        { day: 152, reading: '2 Reyes 8, 9, 10, 11', summary: 'Reyes, Profetas y Exilio' },
        { day: 153, reading: '2 Reyes 12, 13, 14', summary: 'Reyes, Profetas y Exilio' },
        { day: 154, reading: 'Amós 1, 2, 3, 4, 5', summary: 'Reyes, Profetas y Exilio' },
        { day: 155, reading: 'Amós 6, 7, 8, 9', summary: 'Reyes, Profetas y Exilio' },
        { day: 156, reading: '2 Crónicas 26', summary: 'Reyes, Profetas y Exilio' },
        { day: 157, reading: 'Isaías 1, 2, 3, 4', summary: 'Reyes, Profetas y Exilio' },
        { day: 158, reading: 'Isaías 5, 6, 7, 8', summary: 'Reyes, Profetas y Exilio' },
        { day: 159, reading: 'Oseas 1, 2, 3, 4, 5, 6, 7', summary: 'Reyes, Profetas y Exilio' },
        { day: 160, reading: 'Oseas 8, 9, 10, 11, 12, 13, 14', summary: 'Reyes, Profetas y Exilio' },
        { day: 161, reading: 'Miqueas 1, 2, 3, 4, 5, 6, 7', summary: 'Reyes, Profetas y Exilio' },
        { day: 162, reading: '2 Reyes 15, 16, 17', summary: 'Reyes, Profetas y Exilio' },
        { day: 163, reading: '2 Reyes 18, 19', summary: 'Reyes, Profetas y Exilio' },
        { day: 164, reading: 'Isaías 36, 37', summary: 'Reyes, Profetas y Exilio' },
        { day: 165, reading: '2 Reyes 20; Isaías 38, 39', summary: 'Reyes, Profetas y Exilio' },
        { day: 166, reading: 'Isaías 40, 42, 43', summary: 'Reyes, Profetas y Exilio' },
        { day: 167, reading: 'Isaías 44, 45, 46, 47, 48', summary: 'Reyes, Profetas y Exilio' },
        { day: 168, reading: '2 Reyes 21, 22, 23', summary: 'Reyes, Profetas y Exilio' },
        { day: 169, reading: 'Sofonías 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 170, reading: 'Jeremías 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 171, reading: 'Jeremías 4, 5, 6', summary: 'Reyes, Profetas y Exilio' },
        { day: 172, reading: 'Jeremías 7, 8, 9', summary: 'Reyes, Profetas y Exilio' },
        { day: 173, reading: 'Jeremías 10, 11, 12, 13', summary: 'Reyes, Profetas y Exilio' },
        { day: 174, reading: 'Nahúm 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 175, reading: '2 Reyes 24, 25; 2 Crónicas 36', summary: 'Reyes, Profetas y Exilio' },
        { day: 176, reading: 'Habacuc 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 177, reading: 'Lamentaciones 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 178, reading: 'Lamentaciones 4, 5', summary: 'Reyes, Profetas y Exilio' },
        { day: 179, reading: 'Ezequiel 1, 2, 3, 4', summary: 'Reyes, Profetas y Exilio' },
        { day: 180, reading: 'Ezequiel 5, 6, 7, 8', summary: 'Reyes, Profetas y Exilio' },
        { day: 181, reading: 'Ezequiel 9, 10, 11, 12', summary: 'Reyes, Profetas y Exilio' },
        { day: 182, reading: 'Ezequiel 13, 14, 15', summary: 'Reyes, Profetas y Exilio' },
        { day: 183, reading: 'Ezequiel 16, 17, 18', summary: 'Reyes, Profetas y Exilio' },
        { day: 184, reading: 'Ezequiel 19, 20, 21', summary: 'Reyes, Profetas y Exilio' },
        { day: 185, reading: 'Ezequiel 22, 23, 24', summary: 'Reyes, Profetas y Exilio' },
        { day: 186, reading: 'Daniel 1, 2, 3', summary: 'Reyes, Profetas y Exilio' },
        { day: 187, reading: 'Daniel 4, 5, 6', summary: 'Reyes, Profetas y Exilio' },
        { day: 188, reading: 'Daniel 7, 8, 9', summary: 'Reyes, Profetas y Exilio' },
        { day: 189, reading: 'Daniel 10, 11, 12', summary: 'Reyes, Profetas y Exilio' },
        { day: 190, reading: 'Esdras 1, 2, 3', summary: 'Retorno del Exilio' },
        { day: 191, reading: 'Esdras 4, 5, 6', summary: 'Retorno del Exilio' },
        { day: 192, reading: 'Hageo 1, 2', summary: 'Retorno del Exilio' },
        { day: 193, reading: 'Zacarías 1, 2, 3, 4, 5, 6, 7', summary: 'Retorno del Exilio' },
        { day: 194, reading: 'Zacarías 8, 9, 10, 11, 12, 13, 14', summary: 'Retorno del Exilio' },
        { day: 195, reading: 'Ester 1, 2, 3, 4, 5', summary: 'Retorno del Exilio' },
        { day: 196, reading: 'Ester 6, 7, 8, 9, 10', summary: 'Retorno del Exilio' },
        { day: 197, reading: 'Nehemías 1, 2, 3, 4', summary: 'Retorno del Exilio' },
        { day: 198, reading: 'Nehemías 5, 6, 7', summary: 'Retorno del Exilio' },
        { day: 199, reading: 'Nehemías 8, 9, 10', summary: 'Retorno del Exilio' },
        { day: 200, reading: 'Nehemías 11, 12, 13', summary: 'Retorno del Exilio' },
        { day: 201, reading: 'Malaquías 1, 2, 3, 4', summary: 'Retorno del Exilio' },
        { day: 202, reading: 'Esdras 7, 8, 9, 10', summary: 'Retorno del Exilio' },
        { day: 203, reading: 'Nehemías 1, 2, 3, 4', summary: 'Retorno del Exilio' },
        { day: 204, reading: 'Nehemías 5, 6, 7', summary: 'Retorno del Exilio' },
        { day: 205, reading: 'Nehemías 8, 9, 10', summary: 'Retorno del Exilio' },
        { day: 206, reading: 'Nehemías 11, 12, 13', summary: 'Retorno del Exilio' },
        { day: 207, reading: 'Malaquías 1, 2, 3, 4', summary: 'Retorno del Exilio' },
        // ... Días 208–300
        { day: 208, reading: "Juan 1; Marcos 1; Mateo 1; Lucas 1", summary: "Evangelios en Armonía" },
        { day: 209, reading: "Mateo 2, 3; Lucas 2, 3", summary: "Evangelios en Armonía" },
        { day: 210, reading: "Juan 2, 3, 4", summary: "Evangelios en Armonía" },
        { day: 211, reading: "Marcos 2; Mateo 4; Lucas 4, 5; Juan 5", summary: "Evangelios en Armonía" },
        { day: 212, reading: "Marcos 3; Mateo 12; Lucas 6", summary: "Evangelios en Armonía" },
        { day: 213, reading: "Mateo 5, 6, 7", summary: "Evangelios en Armonía" },
        { day: 214, reading: "Mateo 8; Marcos 4, 5", summary: "Evangelios en Armonía" },
        { day: 215, reading: "Marcos 6; Mateo 9, 10", summary: "Evangelios en Armonía" },
        { day: 216, reading: "Mateo 11; Mateo 13", summary: "Evangelios en Armonía" },
        { day: 217, reading: "Marcos 7; Mateo 15", summary: "Evangelios en Armonía" },
        { day: 218, reading: "Mateo 16; Marcos 8; Lucas 9", summary: "Evangelios en Armonía" },
        { day: 219, reading: "Mateo 17; Marcos 9", summary: "Evangelios en Armonía" },
        { day: 220, reading: "Juan 6", summary: "Evangelios en Armonía" },
        { day: 221, reading: "Juan 7, 8", summary: "Evangelios en Armonía" },
        { day: 222, reading: "Juan 9, 10", summary: "Evangelios en Armonía" },
        { day: 223, reading: "Lucas 10, 11", summary: "Evangelios en Armonía" },
        { day: 224, reading: "Lucas 12, 13", summary: "Evangelios en Armonía" },
        { day: 225, reading: "Juan 11", summary: "Evangelios en Armonía" },
        { day: 226, reading: "Lucas 14, 15", summary: "Evangelios en Armonía" },
        { day: 227, reading: "Lucas 16, 17", summary: "Evangelios en Armonía" },
        { day: 228, reading: "Juan 12", summary: "Evangelios en Armonía" },
        { day: 229, reading: "Mateo 21; Marcos 11; Lucas 19", summary: "Evangelios en Armonía" },
        { day: 230, reading: "Mateo 22; Marcos 12; Lucas 20", summary: "Evangelios en Armonía" },
        { day: 231, reading: "Mateo 23, 24; Marcos 13", summary: "Evangelios en Armonía" },
        { day: 232, reading: "Juan 13, 14, 15", "summary": "Evangelios en Armonía" },
        { day: 233, reading: "Juan 16, 17, 18", "summary": "Evangelios en Armonía" },
        { day: 234, reading: "Mateo 26; Marcos 14; Lucas 22", "summary": "Evangelios en Armonía" },
        { day: 235, reading: "Juan 19; Mateo 27; Marcos 15; Lucas 23", "summary": "Evangelios en Armonía" },
        { day: 236, reading: "Juan 20, 21; Mateo 28; Marcos 16; Lucas 24", "summary": "Evangelios en Armonía" },
        { day: 237, reading: "Hechos 1, 2, 3", "summary": "Hechos y las Cartas" },
        { day: 238, reading: "Hechos 4, 5, 6", "summary": "Hechos y las Cartas" },
        { day: 239, reading: "Hechos 7, 8", "summary": "Hechos y las Cartas" },
        { day: 240, reading: "Hechos 9, 10", "summary": "Hechos y las Cartas" },
        { day: 241, reading: "Hechos 11, 12", "summary": "Hechos y las Cartas" },
        { day: 242, reading: "Hechos 13, 14; Gálatas 1, 2, 3", "summary": "Hechos y las Cartas" },
        { day: 243, reading: "Gálatas 4, 5, 6", "summary": "Hechos y las Cartas" },
        { day: 244, reading: "Hechos 15, 16", "summary": "Hechos y las Cartas" },
        { day: 245, reading: "1 Tesalonicenses 1, 2, 3, 4, 5; 2 Tesalonicenses 1, 2, 3;", "summary": "Hechos y las Cartas" },
        { day: 246, reading: "Hechos 17, 18", "summary": "Hechos y las Cartas" },
        { day: 247, reading: "1 Corintios 1, 2, 3, 4, 5, 6, 7, 8", "summary": "Hechos y las Cartas" },
        { day: 248, reading: "1 Corintios 9, 10, 11, 12, 13, 14, 15, 16", "summary": "Hechos y las Cartas" },
        { day: 249, reading: "2 Corintios 1, 2, 3, 4, 5, 6, 7", "summary": "Hechos y las Cartas" },
        { day: 250, reading: "2 Corintios 8, 9, 10, 11, 12, 13", "summary": "Hechos y las Cartas" },
        { day: 251, reading: "Romanos 1, 2, 3, 4, 5, 6, 7, 8", "summary": "Hechos y las Cartas" },
        { day: 252, reading: "Romanos 9, 10, 11, 12, 13, 14, 15, 16", "summary": "Hechos y las Cartas" },
        { day: 253, reading: "Hechos 19, 20", "summary": "Hechos y las Cartas" },
        { day: 254, reading: "Hechos 21, 22, 23", "summary": "Hechos y las Cartas" },
        { day: 255, reading: "Hechos 24, 25, 26", "summary": "Hechos y las Cartas" },
        { day: 256, reading: "Hechos 27, 28", "summary": "Hechos y las Cartas" },
        { day: 257, reading: "Colosenses 1, 2, 3, 4; Filemón 1;", "summary": "Hechos y las Cartas" },
        { day: 258, reading: "Efesios 1, 2, 3, 4, 5, 6;", "summary": "Hechos y las Cartas" },
        { day: 259, reading: "Filipenses 1, 2, 3, 4;", "summary": "Hechos y las Cartas" },
        { day: 260, reading: "1 Timoteo 1, 2, 3, 4, 5, 6", "summary": "Hechos y las Cartas" },
        { day: 261, reading: "Tito 1, 2, 3", "summary": "Hechos y las Cartas" },
        { day: 262, reading: "1 Pedro 1, 2, 3, 4, 5", "summary": "Cartas Generales" },
        { day: 263, reading: "Hebreos 1, 2, 3, 4, 5, 6, 7", "summary": "Cartas Generales" },
        { day: 264, reading: "Hebreos 8, 9, 10, 11, 12, 13", "summary": "Cartas Generales" },
        { day: 265, reading: "2 Timoteo 1, 2, 3, 4", "summary": "Cartas Generales" },
        { day: 266, reading: "2 Pedro 1, 2, 3", "summary": "Cartas Generales" },
        { day: 267, reading: "Judas 1", "summary": "Cartas Generales" },
        { day: 268, reading: "1 Juan 1, 2, 3, 4, 5; 2 Juan 1; 3 Juan 1;", "summary": "Cartas Generales" },
        { day: 269, reading: "Apocalipsis 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 11;", "summary": "Apocalipsis" },
        { day: 270, reading: "Apocalipsis 12, 13, 14, 15, 16, 17, 18, 19 20, 21, 22", "summary": "Apocalipsis" },
    ],
};
