export const aTravesDeLaBibliaIsaias = [
    { "day": 1, "reading": "Isaías 1-3", "summary": "Juicio y llamado al arrepentimiento." },
    { "day": 2, "reading": "Isaías 4-6", "summary": "El remanente de Sion y la visión de Isaías." },
    { "day": 3, "reading": "Isaías 7-9", "summary": "La señal de Emanuel y la profecía del Príncipe de Paz." },
    { "day": 4, "reading": "Isaías 10-12", "summary": "El juicio de Asiria y el reino del renuevo de Isaí." },
    { "day": 5, "reading": "Isaías 13-15", "summary": "Profecías sobre Babilonia, Asiria y Moab." },
    { "day": 6, "reading": "Isaías 16-18", "summary": "Lamento por Moab, profecía sobre Damasco y Cus." },
    { "day": 7, "reading": "Isaías 19-21", "summary": "Profecías sobre Egipto, el desierto del mar y el valle de la visión." },
    { "day": 8, "reading": "Isaías 22-24", "summary": "Profecía sobre Jerusalén, Tiro y el juicio de la tierra." },
    { "day": 9, "reading": "Isaías 25-27", "summary": "Cántico de alabanza y la restauración de Israel." },
    { "day": 10, "reading": "Isaías 28-30", "summary": "Ayes sobre Efraín, Ariel y los hijos rebeldes." },
    { "day": 11, "reading": "Isaías 31-33", "summary": "La futilidad de confiar en Egipto y el rey justo." },
    { "day": 12, "reading": "Isaías 34-36", "summary": "El juicio de las naciones y la liberación de Sion." },
    { "day": 13, "reading": "Isaías 37-39", "summary": "Liberación de Jerusalén y la enfermedad de Ezequías." },
    { "day": 14, "reading": "Isaías 40-42", "summary": "Consuelo para el pueblo de Dios y el Siervo de Jehová." },
    { "day": 15, "reading": "Isaías 43-45", "summary": "El Redentor de Israel y la soberanía de Jehová." },
    { "day": 16, "reading": "Isaías 46-48", "summary": "La caída de los ídolos de Babilonia y la terquedad de Israel." },
    { "day": 17, "reading": "Isaías 49-51", "summary": "El Siervo como luz a las naciones y el consuelo para Sion." },
    { "day": 18, "reading": "Isaías 52-54", "summary": "El heraldo de la paz y el Siervo sufriente." },
    { "day": 19, "reading": "Isaías 55-57", "summary": "Invitación a la gracia y la condenación de la idolatría." },
    { "day": 20, "reading": "Isaías 58-60", "summary": "El verdadero ayuno y la gloria futura de Sion." },
    { "day": 21, "reading": "Isaías 61-63", "summary": "El año de la buena voluntad de Jehová y la venganza de Dios." },
    { "day": 22, "reading": "Isaías 64-66", "summary": "Oración por la misericordia y los nuevos cielos y la nueva tierra." }
];