export const cuaresma2026 = [
    { "day": 1, "reading": "Mateo 1-2", "summary": "La genealogía y el nacimiento de Jesús." },
    { "day": 2, "reading": "Salmos 1-2", "summary": "El justo y el rey ungido." },
    { "day": 3, "reading": "Mateo 3-4", "summary": "El bautismo y la tentación de Jesús." },
    { "day": 4, "reading": "Salmos 3-5", "summary": "Oraciones de confianza en medio de la angustia." },
    { "day": 5, "reading": "Mateo 5", "summary": "El Sermón del Monte: Las Bienaventuranzas." },
    { "day": 6, "reading": "Salmos 6-8", "summary": "Lamento y alabanza." },
    { "day": 7, "reading": "Mateo 6", "summary": "Enseñanzas sobre la oración, el ayuno y las riquezas." },
    { "day": 8, "reading": "Salmos 9-10", "summary": "Alabanza por la justicia de Dios." },
    { "day": 9, "reading": "Mateo 7", "summary": "El juicio, la puerta estrecha y los dos cimientos." },
    { "day": 10, "reading": "Salmos 11-14", "summary": "Confianza en el Señor." },
    { "day": 11, "reading": "Mateo 8", "summary": "Milagros de Jesús: lepra, siervos y tormentas." },
    { "day": 12, "reading": "Salmos 15-17", "summary": "El carácter de los que habitan con Dios." },
    { "day": 13, "reading": "Mateo 9", "summary": "Más milagros y el llamado a Mateo." },
    { "day": 14, "reading": "Salmos 18", "summary": "Cántico de liberación de David." },
    { "day": 15, "reading": "Mateo 10", "summary": "Jesús envía a los doce apóstoles." },
    { "day": 16, "reading": "Salmos 19-21", "summary": "La ley y la gloria de Dios." },
    { "day": 17, "reading": "Mateo 11", "summary": "Jesús y Juan el Bautista." },
    { "day": 18, "reading": "Salmos 22", "summary": "Un salmo de sufrimiento y alabanza (Mesiánico)." },
    { "day": 19, "reading": "Mateo 12", "summary": "Señor del día de reposo y la blasfemia contra el Espíritu." },
    { "day": 20, "reading": "Salmos 23-24", "summary": "El Señor es mi pastor y el Rey de Gloria." },
    { "day": 21, "reading": "Mateo 13", "summary": "Parábolas del Reino." },
    { "day": 22, "reading": "Salmos 25-27", "summary": "Oraciones pidiendo guía y protección." },
    { "day": 23, "reading": "Mateo 14", "summary": "Muerte de Juan el Bautista y alimentación de los 5,000." },
    { "day": 24, "reading": "Salmos 28-30", "summary": "Súplica y acción de gracias." },
    { "day": 25, "reading": "Mateo 15", "summary": "Tradiciones, fe de la cananea y alimentación de los 4,000." },
    { "day": 26, "reading": "Salmos 31-32", "summary": "Refugio en Dios y el gozo del perdón." },
    { "day": 27, "reading": "Mateo 16", "summary": "La confesión de Pedro." },
    { "day": 28, "reading": "Salmos 33-34", "summary": "Alabanza al Creador y al Libertador." },
    { "day": 29, "reading": "Mateo 17", "summary": "La transfiguración." },
    { "day": 30, "reading": "Salmos 35-36", "summary": "Oración pidiendo liberación de los enemigos." },
    { "day": 31, "reading": "Mateo 18-19", "summary": "El perdón y enseñanzas sobre el divorcio y los niños." },
    { "day": 32, "reading": "Salmos 37", "summary": "Confianza en Dios en lugar de envidiar a los malos." },
    { "day": 33, "reading": "Mateo 20-21", "summary": "La entrada triunfal y la purificación del templo." },
    { "day": 34, "reading": "Salmos 40-41", "summary": "Esperanza en el Señor." },
    { "day": 35, "reading": "Mateo 22-23", "summary": "Parábolas y ayes contra los fariseos." },
    { "day": 36, "reading": "Mateo 24-25", "summary": "El discurso del Monte de los Olivos." },
    { "day": 37, "reading": "Salmos 51", "summary": "Salmo de arrepentimiento de David." },
    { "day": 38, "reading": "Mateo 26", "summary": "La última cena, el arresto de Jesús." },
    { "day": 39, "reading": "Mateo 27", "summary": "La crucifixión y muerte de Jesús." },
    { "day": 40, "reading": "Mateo 28", "summary": "La resurrección y la Gran Comisión." }
];