export const elEvangelioDeIsaias = [
    { day: 1, reading: 'Isaías 1', summary: '' },
    { day: 2, reading: 'Isaías 2', summary: '' },
    { day: 3, reading: 'Isaías 5', summary: '' },
    { day: 4, reading: 'Isaías 6', summary: '' },
    { day: 5, reading: 'Isaías 9', summary: '' },
    { day: 6, reading: 'Isaías 11', summary: '' },
    { day: 7, reading: 'Isaías 12', summary: '' },
    { day: 8, reading: 'Isaías 25', summary: '' },
    { day: 9, reading: 'Isaías 26', summary: '' },
    { day: 10, reading: 'Isaías 35', summary: '' },
    { day: 11, reading: 'Isaías 40', summary: '' },
    { day: 12, reading: 'Isaías 42', summary: '' },
    { day: 13, reading: 'Isaías 43', summary: '' },
    { day: 14, reading: 'Isaías 44', summary: '' },
    { day: 15, reading: 'Isaías 49', summary: '' },
    { day: 16, reading: 'Isaías 50', summary: '' },
    { day: 17, reading: 'Isaías 52', summary: '' },
    { day: 18, reading: 'Isaías 53', summary: '' },
    { day: 19, reading: 'Isaías 55', summary: '' },
    { day: 20, reading: 'Isaías 58', summary: '' },
    { day: 21, reading: 'Isaías 60', summary: '' },
    { day: 22, reading: 'Isaías 61', summary: '' },
    { day: 23, reading: 'Isaías 65', summary: '' },
    { day: 24, reading: 'Isaías 66', summary: '' },
];
