export const inmersionEnIsaias = [
    { "day": 1, "reading": "Isaías 1", "summary": "Explora el llamado de Dios al arrepentimiento y la purificación." },
    { "day": 2, "reading": "Isaías 2", "summary": "Contempla la visión del reino futuro de Dios y la exaltación de Jerusalén." },
    { "day": 3, "reading": "Isaías 5", "summary": "Reflexiona sobre la parábola de la viña del Señor y las consecuencias de la injusticia." },
    { "day": 4, "reading": "Isaías 6", "summary": "Sé testigo de la majestuosa visión de Dios que tuvo Isaías y su llamado al ministerio profético." },
    { "day": 5, "reading": "Isaías 7", "summary": "Descubre la señal de Emanuel, una promesa de la protección y fidelidad de Dios." },
    { "day": 6, "reading": "Isaías 9", "summary": "Alégrate con la profecía del nacimiento de un niño que será llamado Príncipe de Paz." },
    { "day": 7, "reading": "Isaías 11", "summary": "Observa la visión del renuevo de Isaí, un rey que reinará con justicia y paz." },
    { "day": 8, "reading": "Isaías 12", "summary": "Únete al cántico de acción de gracias por la salvación y la fortaleza que se encuentran en Dios." },
    { "day": 9, "reading": "Isaías 24", "summary": "Medita sobre el juicio venidero de Dios sobre toda la tierra." },
    { "day": 10, "reading": "Isaías 25", "summary": "Canta alabanzas por la victoria final de Dios sobre la muerte y el sufrimiento." },
    { "day": 11, "reading": "Isaías 26", "summary": "Confía en la promesa de Dios de paz perfecta para aquellos que se mantienen firmes en Él." },
    { "day": 12, "reading": "Isaías 27", "summary": "Aprende sobre la restauración futura de Israel y la derrota de los enemigos de Dios." },
    { "day": 13, "reading": "Isaías 30", "summary": "Recibe la advertencia contra la confianza en el poder humano en lugar de en Dios." },
    { "day": 14, "reading": "Isaías 35", "summary": "Anticipa el glorioso futuro de Sion, donde el desierto florecerá y los redimidos caminarán." },
    { "day": 15, "reading": "Isaías 40", "summary": "Encuentra consuelo en las palabras de Dios a su pueblo, prometiendo fortaleza y renovación." },
    { "day": 16, "reading": "Isaías 42", "summary": "Conoce al Siervo de Jehová, que traerá justicia a las naciones." },
    { "day": 17, "reading": "Isaías 43", "summary": "Descansa en la seguridad de que Dios es el Redentor y Salvador de Israel." },
    { "day": 18, "reading": "Isaías 44", "summary": "Reconoce la soberanía de Jehová como el único Dios verdadero, en contraste con los ídolos sin poder." },
    { "day": 19, "reading": "Isaías 45", "summary": "Maravíllate de cómo Dios usa incluso a los gobernantes paganos como Ciro para cumplir sus propósitos." },
    { "day": 20, "reading": "Isaías 49", "summary": "Comprende el llamado del Siervo a ser una luz para las naciones, trayendo la salvación hasta los confines de la tierra." },
    { "day": 21, "reading": "Isaías 52", "summary": "Escucha las buenas nuevas del heraldo de la paz y la redención de Jerusalén." },
    { "day": 22, "reading": "Isaías 53", "summary": "Contempla la descripción profética del Siervo sufriente que lleva los pecados de muchos." },
    { "day": 23, "reading": "Isaías 54", "summary": "Experimenta la seguridad del amor eterno e inquebrantable de Jehová por su pueblo." },
    { "day": 24, "reading": "Isaías 55", "summary": "Responde a la invitación abierta de Dios a recibir gratuitamente el agua, el vino y la leche de su gracia." },
    { "day": 25, "reading": "Isaías 58", "summary": "Aprende la diferencia entre el ayuno religioso y la verdadera adoración que se deleita en la justicia y la misericordia." },
    { "day": 26, "reading": "Isaías 60", "summary": "Visualiza la futura gloria de Sion, cuando la luz de Dios atraerá a las naciones hacia ella." },
    { "day": 27, "reading": "Isaías 61", "summary": "Escucha el anuncio del año de la buena voluntad de Jehová, trayendo buenas nuevas a los pobres y libertad a los cautivos." },
    { "day": 28, "reading": "Isaías 63", "summary": "Reflexiona sobre la dualidad de la ira y la misericordia de Dios." },
    { "day": 29, "reading": "Isaías 65", "summary": "Anhela la promesa de nuevos cielos y una nueva tierra, donde reinarán la justicia y la alegría." },
    { "day": 30, "reading": "Isaías 66", "summary": "Prepárate para el juicio final de Dios y la reunión de sus verdaderos adoradores de todas las naciones." }
];